
spring:
  h2:
    console:
      path: "/h2-console"
      enabled: true
management:
  server:
    port: 9292
  endpoint:
    shutdown:
      enabled: true 
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: hello-actuator
    company: ebjt

logging:
  level:
    com.hae.demo: debug